return {
    ["\\"] = "com.apple.Passwords",
    ["a"] = "com.apple.Terminal",
    ["b"] = "net.imput.helium",
    ["c"] = "com.apple.iCal",
    ["d"] = "com.hnc.Discord",
    ["e"] = "com.apple.FaceTime",
    ["f"] = "com.apple.finder",
    ["g"] = "com.anthropic.claudefordesktop",
    ["i"] = "com.apple.MobileSMS",
    ["m"] = "com.apple.mail",
    ["n"] = "net.shinyfrog.bear",
    ["o"] = "md.obsidian",
    ["p"] = "com.microsoft.Powerpoint",
    ["s"] = "com.apple.systempreferences",
    ["t"] = "ru.keepcoder.Telegram",
    ["w"] = "net.whatsapp.WhatsApp",
    ["x"] = "com.microsoft.Excel",
    ["y"] = "com.spotify.client",
    ["z"] = "dev.zed.Zed",
}
